categories: [Phylogenetics, RNA, Transcriptomics]
description: countings codons and amino acids - permutation tests
long_description: this tool works either with the outputs of the tools concatphyl
  or cds_search. It proceeds to count codons and amino acids within a set of fasta sequences. It
  takes into account amino acid properties and do some permutations tests
name: mutcount
owner: abims-sbr
remote_repository_url: htpps://github.com/abims-sbr/adaptearch
